name: syn # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for Syntesys # 79 char long summary
description: |
  SYN App Syntesys.

  Get current syn:-
    $ syn
  Get current syn in login
    $ syn --login
  Get current syn in logout
    $ syn --logout


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

parts:
  syn:
    # See 'snapcraft plugins'
    plugin: nodejs
    source: .

apps:
  syn:
    command: node index.js # bin/hello


# build-packages:
#   - git
#   - less
#   - libcurl3-gnutls
#   - liberror-perl